apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: workload-automation
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4=  # Base64 encoded value of 'admin'
  DATABASE_PASSWORD: YWRtaW4=  # Base64 encoded value of 'admin'